# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default
  vmImage: windows-latest
  
variables:
  buildConfiguration: 'Release'
  dotnetSdkVersion: '7.0.400'

steps:
- task: UseDotNet@2
  inputs:
    version: '$(dotnetSdkVersion)'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
  displayName: Build Code
  enabled: false

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    projects: '**/Orien.PWS.Web.csproj'
    arguments: '--configuration $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)'
  displayName: Publish Web App

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: Publish Build Artifact

# - task: AzureRmWebAppDeployment@4
#   inputs:
#     ConnectionType: 'AzureRM'
#     azureSubscription: 'Free Trial(6502d064-82cc-4fbf-8582-b59191fa9f9a)'
#     appType: 'webApp'
#     WebAppName: 'PayYourShare'
#     packageForLinux: '$(Build.ArtifactStagingDirectory)/Orien.PYS.Web.zip'